defaults: &defaults
  site_name: TubeHub
  cookie_name: __tubehub
  cookie_key: 1209iFNSJDNF*8&Y&YHH__
  
production:
  <<: *defaults
  # Backend port for websockets
  websocket_port: 5000
development:  
  <<: *defaults
test:
  <<: *defaults