development:
  adapter: sqlite3
  host: localhost
  username: root 
  password:
  database: db/tube.sqlite3

test:
  adapter: sqlite3
  database: db/tube-test.sqlite3

production:
  adapter: sqlite3
  database: db/tube.sqlite3

